#!/usr/bin/env python3
"""
Advanced Excel to PowerPoint Converter with Chart Extraction
Extracts actual charts from Excel and converts them to PowerPoint

This script properly handles:
- Real Excel charts (not just data-based recreation)
- Multiple chart types (bar, line, pie, area, scatter, combo, etc.)
- Chart images and formatting
- Multiple sheets and multiple charts per sheet
"""

import sys
import os
from pathlib import Path
from io import BytesIO
import openpyxl
from openpyxl.chart import BarChart, LineChart, PieChart, AreaChart, ScatterChart
from openpyxl.drawing.image import Image as OpenpyxlImage
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE
from pptx.dml.color import RGBColor
from PIL import Image as PILImage
import io


class ExcelToPPTConverter:
    """Convert Excel files with charts to PowerPoint presentations"""

    # Map openpyxl chart types to PowerPoint chart types
    CHART_TYPE_MAP = {
        'BarChart': XL_CHART_TYPE.BAR_CLUSTERED,
        'BarChart3D': XL_CHART_TYPE.THREE_D_BAR_CLUSTERED,
        'LineChart': XL_CHART_TYPE.LINE,
        'LineChart3D': XL_CHART_TYPE.THREE_D_LINE,
        'PieChart': XL_CHART_TYPE.PIE,
        'PieChart3D': XL_CHART_TYPE.THREE_D_PIE,
        'AreaChart': XL_CHART_TYPE.AREA,
        'AreaChart3D': XL_CHART_TYPE.THREE_D_AREA,
        'ScatterChart': XL_CHART_TYPE.XY_SCATTER,
        'BubbleChart': XL_CHART_TYPE.BUBBLE,
    }

    def __init__(self, excel_path):
        self.excel_path = Path(excel_path)
        self.wb = openpyxl.load_workbook(excel_path)
        self.prs = Presentation()
        self.prs.slide_width = Inches(10)
        self.prs.slide_height = Inches(7.5)

    def add_title_slide(self):
        """Add title slide with file information"""
        blank_slide_layout = self.prs.slide_layouts[6]  # Blank layout
        slide = self.prs.slides.add_slide(blank_slide_layout)

        # Set dark background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(30, 41, 59)  # Slate 800

        # Title
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(2), Inches(9), Inches(1)
        )
        title_frame = title_box.text_frame
        title_frame.text = "Excel Charts & Data Presentation"
        title_paragraph = title_frame.paragraphs[0]
        title_paragraph.font.size = Pt(40)
        title_paragraph.font.bold = True
        title_paragraph.font.color.rgb = RGBColor(255, 255, 255)
        title_paragraph.alignment = PP_ALIGN.CENTER

        # Subtitle
        subtitle_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(3.2), Inches(9), Inches(0.6)
        )
        subtitle_frame = subtitle_box.text_frame
        subtitle_frame.text = self.excel_path.stem
        subtitle_paragraph = subtitle_frame.paragraphs[0]
        subtitle_paragraph.font.size = Pt(24)
        subtitle_paragraph.font.color.rgb = RGBColor(167, 139, 250)  # Purple
        subtitle_paragraph.alignment = PP_ALIGN.CENTER

        # Footer
        footer_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(4), Inches(9), Inches(0.8)
        )
        footer_frame = footer_box.text_frame
        footer_frame.text = f"Generated by InsightSheet\n{len(self.wb.sheetnames)} sheets"
        footer_paragraph = footer_frame.paragraphs[0]
        footer_paragraph.font.size = Pt(14)
        footer_paragraph.font.color.rgb = RGBColor(148, 163, 184)  # Slate 400
        footer_paragraph.alignment = PP_ALIGN.CENTER

    def add_section_slide(self, sheet_name, chart_count, row_count, col_count):
        """Add section slide for each worksheet"""
        blank_slide_layout = self.prs.slide_layouts[6]
        slide = self.prs.slides.add_slide(blank_slide_layout)

        # Set background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = RGBColor(51, 65, 85)  # Slate 700

        # Sheet name
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(2.5), Inches(9), Inches(1)
        )
        title_frame = title_box.text_frame
        title_frame.text = sheet_name
        title_paragraph = title_frame.paragraphs[0]
        title_paragraph.font.size = Pt(48)
        title_paragraph.font.bold = True
        title_paragraph.font.color.rgb = RGBColor(255, 255, 255)
        title_paragraph.alignment = PP_ALIGN.CENTER

        # Statistics
        stats_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(3.8), Inches(9), Inches(0.5)
        )
        stats_frame = stats_box.text_frame
        stats_frame.text = f"{chart_count} chart(s) • {row_count} rows • {col_count} columns"
        stats_paragraph = stats_frame.paragraphs[0]
        stats_paragraph.font.size = Pt(20)
        stats_paragraph.font.color.rgb = RGBColor(167, 139, 250)
        stats_paragraph.alignment = PP_ALIGN.CENTER

    def extract_chart_data(self, chart):
        """Extract data from an Excel chart for recreation in PPT"""
        series_data = []
        labels = []

        try:
            for series in chart.series:
                series_info = {
                    'name': '',
                    'values': [],
                    'categories': []
                }

                # Get series name
                if series.title:
                    if hasattr(series.title, 'strRef') and series.title.strRef:
                        if series.title.strRef.strCache:
                            series_info['name'] = series.title.strRef.strCache.pt[0].v if series.title.strRef.strCache.pt else ''
                    elif hasattr(series.title, 'v'):
                        series_info['name'] = series.title.v

                # Get values
                if hasattr(series, 'val') and series.val:
                    if hasattr(series.val, 'numRef') and series.val.numRef:
                        if series.val.numRef.numCache:
                            for pt in series.val.numRef.numCache.pt:
                                try:
                                    series_info['values'].append(float(pt.v))
                                except (ValueError, AttributeError):
                                    series_info['values'].append(0)

                # Get categories (labels)
                if hasattr(series, 'cat') and series.cat:
                    if hasattr(series.cat, 'strRef') and series.cat.strRef:
                        if series.cat.strRef.strCache:
                            for pt in series.cat.strRef.strCache.pt:
                                if pt.v not in labels:
                                    labels.append(pt.v)
                                series_info['categories'].append(pt.v)

                if series_info['values']:
                    series_data.append(series_info)

        except Exception as e:
            print(f"  Warning: Could not extract chart data: {e}")

        return series_data, labels

    def add_chart_slide(self, sheet_name, chart, chart_idx):
        """Add a slide with the chart recreated"""
        # Use blank layout
        blank_slide_layout = self.prs.slide_layouts[6]
        slide = self.prs.slides.add_slide(blank_slide_layout)

        # Add title
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.3), Inches(9), Inches(0.5)
        )
        title_frame = title_box.text_frame

        chart_type_name = type(chart).__name__
        chart_title = ""

        # Get chart title if available
        if hasattr(chart, 'title') and chart.title:
            if hasattr(chart.title, 'tx') and chart.title.tx:
                if hasattr(chart.title.tx, 'rich') and chart.title.tx.rich:
                    try:
                        for p in chart.title.tx.rich.p:
                            for r in p.r:
                                if hasattr(r, 't'):
                                    chart_title += r.t
                    except:
                        chart_title = chart_type_name
                else:
                    chart_title = chart_type_name
            else:
                chart_title = chart_type_name
        else:
            chart_title = chart_type_name

        title_frame.text = f"{sheet_name} - {chart_title}"
        title_paragraph = title_frame.paragraphs[0]
        title_paragraph.font.size = Pt(24)
        title_paragraph.font.bold = True
        title_paragraph.font.color.rgb = RGBColor(30, 41, 59)

        # Extract chart data
        series_data, labels = self.extract_chart_data(chart)

        if not series_data or not labels:
            # Add text explaining chart couldn't be extracted
            note_box = slide.shapes.add_textbox(
                Inches(2), Inches(3), Inches(6), Inches(1)
            )
            note_frame = note_box.text_frame
            note_frame.text = f"⚠️ Chart type '{chart_type_name}' detected but data extraction failed.\nConsider using Windows backend with Excel COM for best results."
            note_paragraph = note_frame.paragraphs[0]
            note_paragraph.font.size = Pt(14)
            note_paragraph.font.color.rgb = RGBColor(239, 68, 68)  # Red
            note_paragraph.alignment = PP_ALIGN.CENTER
            return

        # Determine chart type
        ppt_chart_type = self.CHART_TYPE_MAP.get(
            chart_type_name,
            XL_CHART_TYPE.COLUMN_CLUSTERED
        )

        # Create chart data
        chart_data = CategoryChartData()
        chart_data.categories = labels[:15]  # Limit to 15 categories

        for series in series_data[:6]:  # Limit to 6 series
            values = series['values'][:15]  # Match categories length
            # Pad or truncate values to match categories
            while len(values) < len(chart_data.categories):
                values.append(0)
            chart_data.add_series(
                series['name'] or 'Series',
                values[:len(chart_data.categories)]
            )

        # Add chart to slide
        try:
            x, y, cx, cy = Inches(0.5), Inches(1.0), Inches(9), Inches(5)
            graphic_frame = slide.shapes.add_chart(
                ppt_chart_type, x, y, cx, cy, chart_data
            )

            ppt_chart = graphic_frame.chart
            ppt_chart.has_legend = True
            ppt_chart.legend.position = 2  # Right

        except Exception as e:
            print(f"  Error adding chart to slide: {e}")
            # Add error message to slide
            note_box = slide.shapes.add_textbox(
                Inches(2), Inches(3), Inches(6), Inches(1)
            )
            note_frame = note_box.text_frame
            note_frame.text = f"⚠️ Error creating {chart_type_name}: {str(e)}"
            note_paragraph = note_frame.paragraphs[0]
            note_paragraph.font.size = Pt(14)
            note_paragraph.font.color.rgb = RGBColor(239, 68, 68)

    def add_data_table_slide(self, sheet_name, worksheet):
        """Add a slide with data table from worksheet"""
        blank_slide_layout = self.prs.slide_layouts[6]
        slide = self.prs.slides.add_slide(blank_slide_layout)

        # Add title
        title_box = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.3), Inches(9), Inches(0.5)
        )
        title_frame = title_box.text_frame
        title_frame.text = f"{sheet_name} - Data Overview"
        title_paragraph = title_frame.paragraphs[0]
        title_paragraph.font.size = Pt(24)
        title_paragraph.font.bold = True
        title_paragraph.font.color.rgb = RGBColor(30, 41, 59)

        # Get data
        data = []
        for row_idx, row in enumerate(worksheet.iter_rows(values_only=True)):
            if row_idx >= 21:  # Limit to 20 rows + 1 header
                break
            # Get first 10 columns
            row_data = [str(cell) if cell is not None else '' for cell in row[:10]]
            if any(cell for cell in row_data):  # Skip empty rows
                data.append(row_data)

        if not data:
            return

        # Create table
        rows = min(len(data), 20)
        cols = min(len(data[0]), 10)

        x, y, cx, cy = Inches(0.4), Inches(1), Inches(9.2), Inches(5.5)

        table = slide.shapes.add_table(rows, cols, x, y, cx, cy).table

        # Fill table
        for row_idx in range(rows):
            for col_idx in range(cols):
                if row_idx < len(data) and col_idx < len(data[row_idx]):
                    cell = table.cell(row_idx, col_idx)
                    cell.text = str(data[row_idx][col_idx])[:50]  # Limit cell content
                    cell.text_frame.paragraphs[0].font.size = Pt(9)

                    # Header row styling
                    if row_idx == 0:
                        cell.fill.solid()
                        cell.fill.fore_color.rgb = RGBColor(241, 245, 249)  # Slate 100
                        cell.text_frame.paragraphs[0].font.bold = True

    def convert(self, output_path=None):
        """Main conversion method"""
        if output_path is None:
            output_path = self.excel_path.with_name(
                f"{self.excel_path.stem}_presentation.pptx"
            )

        print(f"Converting {self.excel_path} to PowerPoint...")
        print(f"Found {len(self.wb.sheetnames)} sheets")

        # Add title slide
        self.add_title_slide()

        total_charts = 0
        total_slides = 1

        # Process each sheet
        for sheet_idx, sheet_name in enumerate(self.wb.sheetnames):
            print(f"\nProcessing sheet {sheet_idx + 1}/{len(self.wb.sheetnames)}: {sheet_name}")
            worksheet = self.wb[sheet_name]

            # Get charts in this sheet
            charts = worksheet._charts if hasattr(worksheet, '_charts') else []

            # Get dimensions
            max_row = worksheet.max_row
            max_col = worksheet.max_column

            # Add section slide
            self.add_section_slide(sheet_name, len(charts), max_row, max_col)
            total_slides += 1

            # Add data table slide
            self.add_data_table_slide(sheet_name, worksheet)
            total_slides += 1

            # Process charts
            if charts:
                print(f"  Found {len(charts)} chart(s)")
                for chart_idx, chart in enumerate(charts, 1):
                    chart_type = type(chart).__name__
                    print(f"    Chart {chart_idx}: {chart_type}")
                    self.add_chart_slide(sheet_name, chart, chart_idx)
                    total_charts += 1
                    total_slides += 1
            else:
                print(f"  No charts found")

        # Save presentation
        self.prs.save(output_path)

        print(f"\n✅ Conversion complete!")
        print(f"   Output: {output_path}")
        print(f"   Total slides: {total_slides}")
        print(f"   Charts extracted: {total_charts}")

        return output_path


def main():
    """Main entry point"""
    if len(sys.argv) < 2:
        print("Usage: python excel_to_ppt_with_charts.py <excel_file> [output_file]")
        print("\nExample:")
        print("  python excel_to_ppt_with_charts.py report.xlsx")
        print("  python excel_to_ppt_with_charts.py report.xlsx presentation.pptx")
        sys.exit(1)

    excel_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None

    if not os.path.exists(excel_file):
        print(f"Error: File '{excel_file}' not found")
        sys.exit(1)

    try:
        converter = ExcelToPPTConverter(excel_file)
        converter.convert(output_file)
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
