/**
 * Oracle Cloud HCM: HCM Data Loader (HDL) files.
 *
 * Each business object is one pipe-delimited .dat file (Worker.dat, Job.dat…).
 * Inside a file, every component (Worker, PersonName, WorkRelationship,
 * WorkTerms, Assignment…) gets a METADATA line naming its attributes, then one
 * MERGE line per record, in parent-before-child order. The entities below that
 * share a `datFile` are written into that file in the order listed.
 *
 * Keys: every record has SourceSystemOwner + SourceSystemId. The IDs are built
 * deterministically from the source key (PER_1001, ASG_1001…), so a second load
 * of the same extract updates the same records instead of creating duplicates,
 * and children point at parents with "PersonId(SourceSystemId)".
 *
 * Effective dating: Assignment history is written as date-effective rows with
 * the same SourceSystemId; each row ends the day before the next one starts
 * (the last ends 4712/12/31), in chronological order.
 *
 * Attribute names follow the standard HDL business objects; compare with your
 * pod's View Business Objects page (and add flexfields) before loading.
 */
import { countryA2 } from '../engine';

const END_OF_TIME = '4712-12-31';
const ssid = (prefix, c, suffix = '') => `${prefix}_${c.get('employee_id')}${suffix}`;
const owner = { id: 'SourceSystemOwner', label: 'Source system owner', derive: (c) => c.settings.hdlSourceSystemOwner, required: true };
const legislation = (c) => countryA2(c.job('company_country') || c.orgExtra('company', c.job('company_code'), 'company_country') || c.get('address_country') || c.settings.hdlLegislationCode) || c.settings.hdlLegislationCode;
const legalEmployer = (c, from = 'job') => c.orgName('company', c[from]('company_code')) || c[from]('company_code');
const departmentName = (c, from = 'get') => c.orgName('department', c[from]('department_code')) || c[from]('department_code');
const assignmentNo = (c, id) => `${c.settings.hdlAssignmentPrefix}${id || c.get('employee_id')}`;

const foundation = (id, label, list, datFile, component, extra) => ({
  id,
  label,
  stage: 'Foundation data',
  grain: `org:${list}`,
  datFile,
  component,
  dependsOn: [],
  fields: [
    { id: 'SourceSystemOwner', label: 'Source system owner', derive: (c) => c.settings.hdlSourceSystemOwner, required: true },
    { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => `${component.toUpperCase().slice(0, 4)}_${c.code}`, required: true },
    { id: 'EffectiveStartDate', label: 'Effective start', derive: (c) => c.settings.foundationStartDate, date: true, required: true },
    { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
    ...extra,
  ],
});

export const ORACLE_HCM = {
  id: 'oracle',
  label: 'Oracle Cloud HCM (HDL)',
  short: 'Oracle HCM',
  format: 'hdl',
  orgRefs: { Location: 'location', Job: 'job', Organization: 'department' },
  reconcile: {
    employees: 'Worker',
    employeeField: 'PersonNumber',
    money: [['Salary', 'salary_amount', 'Salary', 'SalaryAmount', '__none']],
  },
  defaultSettings: {
    dateFormat: 'yyyy/MM/dd',
    hdlSourceSystemOwner: 'LEGACY',
    hdlLegislationCode: 'GB',
    hdlBusinessUnit: '',
    hdlSetCode: 'COMMON',
    hdlAssignmentPrefix: 'E',
    hdlSalaryBasis: '',
    hdlHireAction: 'HIRE',
    hdlJobChangeAction: 'JOB_CHANGE',
    hdlTransferAction: 'TRANSFER',
    hdlDataChangeAction: 'ASG_CHANGE',
    hdlSalaryAction: 'CHANGE_SALARY',
    hdlTerminationAction: 'TERMINATION',
  },
  settingsFields: [
    ['hdlSourceSystemOwner', 'Source system owner', 'Registered in Setup and Maintenance (HRC_SOURCE_SYSTEM_OWNER).'],
    ['hdlLegislationCode', 'Default legislation code', 'When neither the legal employer nor the address gives one, e.g. GB, US, IN.'],
    ['hdlBusinessUnit', 'Business unit short code', 'For WorkTerms and Assignment.'],
    ['hdlSetCode', 'Reference data set code', 'For jobs, locations and departments (COMMON by default).'],
    ['hdlAssignmentPrefix', 'Assignment number prefix', 'Assignment number = prefix + person number.'],
    ['hdlSalaryBasis', 'Salary basis name', 'Used when the extract has no pay component.'],
    ['hdlHireAction', 'Hire action code', 'ActionCode on Worker, WorkRelationship and the first assignment row.'],
    ['hdlJobChangeAction', 'Job change action code', 'Later rows where the job, title or grade changed.'],
    ['hdlTransferAction', 'Transfer action code', 'Later rows where the department, location or legal employer changed.'],
    ['hdlDataChangeAction', 'Assignment change action code', 'Any other later row.'],
    ['hdlTerminationAction', 'Termination action code', 'Used in the terminations load.'],
  ],
  readmeNotes: (settings) => [
    'HDL loads business objects as .dat files inside a .zip. hdl_upload/ holds the',
    'files in load order: foundation objects (Location, Organization, Job) first, then',
    'Worker.dat, then Salary.dat. Zip and import each in that order (Data Exchange >',
    'Import and Load Data), or put them in one zip if your pod allows it.',
    'hdl_terminations/Worker.dat ends the work relationships of leavers: load it after',
    'the hires have completed.',
    `SourceSystemOwner is ${settings.hdlSourceSystemOwner}; SourceSystemIds are built from the source key`,
    '(PER_<id>, ASG_<id>…) so reloading the same extract updates the same records.',
    'Assignment history is date-effective: rows end the day before the next change, the',
    'last ends 4712/12/31. Dates are written YYYY/MM/DD as HDL expects.',
    'Bank details and payroll balances are not in this package (load them with the',
    'payroll HDL objects); they are listed in issues.csv if present in the extract.',
  ],
  entities: [
    foundation('Location', 'Locations', 'location', 'Location.dat', 'Location', [
      { id: 'SetCode', label: 'Set code', derive: (c) => c.settings.hdlSetCode, required: true },
      { id: 'LocationCode', label: 'Location code', derive: (c) => c.code, required: true },
      { id: 'LocationName', label: 'Location name', derive: (c) => c.name || c.code, required: true },
      { id: 'ActiveStatus', label: 'Status', derive: () => 'A', required: true },
      { id: 'Country', label: 'Country', derive: (c) => countryA2(c.extra.location_country) },
    ]),
    foundation('Organization', 'Departments', 'department', 'Organization.dat', 'Organization', [
      { id: 'Name', label: 'Name', derive: (c) => c.name || c.code, required: true },
      { id: 'ClassificationCode', label: 'Classification', derive: () => 'DEPARTMENT', required: true },
      { id: 'SetCode', label: 'Set code', derive: (c) => c.settings.hdlSetCode },
    ]),
    foundation('Job', 'Jobs', 'job', 'Job.dat', 'Job', [
      { id: 'SetCode', label: 'Set code', derive: (c) => c.settings.hdlSetCode, required: true },
      { id: 'JobCode', label: 'Job code', derive: (c) => c.code, required: true },
      { id: 'Name', label: 'Name', derive: (c) => c.name || c.code, required: true },
      { id: 'ActiveStatus', label: 'Status', derive: () => 'A', required: true },
    ]),
    {
      id: 'Worker',
      label: 'Worker',
      stage: 'People',
      grain: 'employee',
      datFile: 'Worker.dat',
      component: 'Worker',
      dependsOn: ['Location', 'Organization', 'Job'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('PER', c), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', from: 'hire_date', date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'PersonNumber', label: 'Person number', from: 'employee_id', required: true },
        { id: 'StartDate', label: 'Start date', derive: (c) => c.get('original_hire_date') || c.get('hire_date'), date: true, required: true },
        { id: 'DateOfBirth', label: 'Date of birth', from: 'date_of_birth', date: true },
        { id: 'CountryOfBirth', label: 'Country of birth', derive: (c) => countryA2(c.get('country_of_birth')) },
        { id: 'TownOfBirth', label: 'Town of birth', from: 'place_of_birth' },
        { id: 'ActionCode', label: 'Action', derive: (c) => c.settings.hdlHireAction, required: true },
      ],
    },
    {
      id: 'PersonName',
      label: 'Person names',
      stage: 'People',
      grain: 'employee',
      datFile: 'Worker.dat',
      component: 'PersonName',
      dependsOn: ['Worker'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('NAME', c), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', from: 'hire_date', date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'LegislationCode', label: 'Legislation', derive: legislation, required: true },
        { id: 'NameType', label: 'Name type', derive: () => 'GLOBAL', required: true },
        { id: 'FirstName', label: 'First name', from: 'first_name' },
        { id: 'MiddleNames', label: 'Middle names', from: 'middle_name' },
        { id: 'LastName', label: 'Last name', from: 'last_name', required: true },
        { id: 'KnownAs', label: 'Known as', from: 'preferred_name' },
        { id: 'Title', label: 'Title', from: 'salutation' },
      ],
    },
    {
      id: 'PersonLegislativeData',
      label: 'Legislative data (sex, marital status)',
      stage: 'People',
      grain: 'employee',
      datFile: 'Worker.dat',
      component: 'PersonLegislativeData',
      dependsOn: ['Worker'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('LEG', c), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', from: 'hire_date', date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'LegislationCode', label: 'Legislation', derive: legislation, required: true },
        { id: 'Sex', label: 'Sex', from: 'gender' },
        { id: 'MaritalStatus', label: 'Marital status', from: 'marital_status' },
      ],
    },
    {
      id: 'PersonEmail',
      label: 'Emails',
      stage: 'Contact',
      grain: 'email',
      datFile: 'Worker.dat',
      component: 'PersonEmail',
      dependsOn: ['Worker'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('EMAIL', c, c.emailType === c.settings.personalEmailType ? '_H1' : '_W1'), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'DateFrom', label: 'Date from', from: 'hire_date', date: true, required: true },
        { id: 'EmailType', label: 'Email type', derive: (c) => (c.emailType === c.settings.personalEmailType ? 'H1' : 'W1'), required: true },
        { id: 'EmailAddress', label: 'Email address', derive: (c) => c.email, required: true },
        { id: 'PrimaryFlag', label: 'Primary', derive: (c) => (c.isPrimary ? 'Y' : 'N'), required: true },
      ],
    },
    {
      id: 'PersonPhone',
      label: 'Phones',
      stage: 'Contact',
      grain: 'phone',
      datFile: 'Worker.dat',
      component: 'PersonPhone',
      dependsOn: ['Worker'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('PHONE', c, '_W1'), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'DateFrom', label: 'Date from', from: 'hire_date', date: true, required: true },
        { id: 'PhoneType', label: 'Phone type', derive: () => 'W1', required: true },
        { id: 'PhoneNumber', label: 'Phone number', from: 'phone_work', required: true },
        { id: 'PrimaryFlag', label: 'Primary', derive: () => 'Y', required: true },
      ],
    },
    {
      id: 'PersonAddress',
      label: 'Addresses',
      stage: 'Contact',
      grain: 'address',
      datFile: 'Worker.dat',
      component: 'PersonAddress',
      dependsOn: ['Worker'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('ADDR', c, '_HOME'), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', from: 'hire_date', date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'AddressType', label: 'Address type', derive: () => 'HOME', required: true },
        { id: 'AddressLine1', label: 'Address line 1', from: 'address_line1', required: true },
        { id: 'AddressLine2', label: 'Address line 2', from: 'address_line2' },
        { id: 'TownOrCity', label: 'Town or city', from: 'city' },
        { id: 'Region1', label: 'Region', from: 'state' },
        { id: 'PostalCode', label: 'Postal code', from: 'postal_code' },
        { id: 'Country', label: 'Country', derive: (c) => countryA2(c.get('address_country')), required: true },
        { id: 'PrimaryFlag', label: 'Primary', derive: () => 'Y', required: true },
      ],
    },
    {
      id: 'WorkRelationship',
      label: 'Work relationships',
      stage: 'Employment',
      grain: 'employee',
      datFile: 'Worker.dat',
      component: 'WorkRelationship',
      dependsOn: ['Worker'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('WR', c), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'LegalEmployerName', label: 'Legal employer', derive: (c) => legalEmployer(c, 'firstJob'), required: true },
        { id: 'DateStart', label: 'Start date', from: 'hire_date', date: true, required: true },
        { id: 'WorkerType', label: 'Worker type', derive: () => 'E', required: true },
        { id: 'PrimaryFlag', label: 'Primary', derive: () => 'Y', required: true },
        { id: 'ActionCode', label: 'Action', derive: (c) => c.settings.hdlHireAction, required: true },
      ],
    },
    {
      id: 'WorkTerms',
      label: 'Work terms',
      stage: 'Employment',
      grain: 'employee',
      datFile: 'Worker.dat',
      component: 'WorkTerms',
      dependsOn: ['WorkRelationship'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('ET', c), required: true },
        { id: 'PeriodOfServiceId(SourceSystemId)', label: 'Work relationship', derive: (c) => ssid('WR', c), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'ActionCode', label: 'Action', derive: (c) => c.settings.hdlHireAction, required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', from: 'hire_date', date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'EffectiveSequence', label: 'Effective sequence', derive: () => '1', required: true },
        { id: 'EffectiveLatestChange', label: 'Latest change', derive: () => 'Y', required: true },
        { id: 'AssignmentType', label: 'Assignment type', derive: () => 'ET', required: true },
        { id: 'AssignmentNumber', label: 'Assignment number', derive: (c) => `ET${assignmentNo(c)}`, required: true },
        { id: 'AssignmentStatusTypeCode', label: 'Assignment status', derive: () => 'ACTIVE_PROCESS', required: true },
        { id: 'BusinessUnitShortCode', label: 'Business unit', derive: (c) => c.settings.hdlBusinessUnit, required: true, setting: 'hdlBusinessUnit' },
        { id: 'LegalEmployerName', label: 'Legal employer', derive: (c) => legalEmployer(c, 'firstJob'), required: true },
        { id: 'PersonTypeCode', label: 'Person type', derive: () => 'Employee', required: true },
      ],
    },
    {
      id: 'Assignment',
      label: 'Assignments (date-effective history)',
      stage: 'Employment',
      grain: 'job',
      datFile: 'Worker.dat',
      component: 'Assignment',
      dependsOn: ['WorkTerms'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('ASG', c), required: true },
        { id: 'WorkTermsAssignmentId(SourceSystemId)', label: 'Work terms', derive: (c) => ssid('ET', c), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'ActionCode', label: 'Action', derive: (c) => ({ hire: c.settings.hdlHireAction, jobChange: c.settings.hdlJobChangeAction, transfer: c.settings.hdlTransferAction }[c.eventKind] || c.settings.hdlDataChangeAction), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', derive: (c) => c.effectiveDate, date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: (c) => c.endDate || END_OF_TIME, date: true, required: true },
        { id: 'EffectiveSequence', label: 'Effective sequence', derive: (c) => String(c.seq || 1), required: true },
        { id: 'EffectiveLatestChange', label: 'Latest change', derive: () => 'Y', required: true },
        { id: 'AssignmentType', label: 'Assignment type', derive: () => 'E', required: true },
        { id: 'AssignmentNumber', label: 'Assignment number', derive: (c) => assignmentNo(c), required: true },
        { id: 'AssignmentStatusTypeCode', label: 'Assignment status', derive: () => 'ACTIVE_PROCESS', required: true },
        { id: 'BusinessUnitShortCode', label: 'Business unit', derive: (c) => c.settings.hdlBusinessUnit, required: true, setting: 'hdlBusinessUnit' },
        { id: 'LegalEmployerName', label: 'Legal employer', derive: (c) => c.orgName('company', c.get('company_code')) || c.get('company_code'), required: true },
        { id: 'JobCode', label: 'Job code', from: 'job_code', ref: 'Job' },
        { id: 'DepartmentName', label: 'Department', derive: (c) => departmentName(c), ref: 'Organization', refValue: (c) => c.get('department_code') },
        { id: 'LocationCode', label: 'Location code', from: 'location_code', ref: 'Location' },
        { id: 'GradeCode', label: 'Grade code', from: 'pay_grade' },
        { id: 'NormalHours', label: 'Normal hours', from: 'standard_hours' },
        { id: 'Frequency', label: 'Hours frequency', derive: (c) => (c.get('standard_hours') ? 'W' : '') },
        { id: 'PrimaryFlag', label: 'Primary', derive: () => 'Y', required: true },
        { id: 'PersonTypeCode', label: 'Person type', derive: () => 'Employee', required: true },
      ],
    },
    {
      id: 'AssignmentSupervisor',
      label: 'Line managers',
      stage: 'Employment',
      grain: 'employee',
      datFile: 'Worker.dat',
      component: 'AssignmentSupervisor',
      dependsOn: ['Assignment'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('SUP', c), required: true },
        { id: 'AssignmentId(SourceSystemId)', label: 'Assignment', derive: (c) => ssid('ASG', c), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', derive: (c) => c.latestJobDate, date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'ManagerType', label: 'Manager type', derive: () => 'LINE_MANAGER', required: true },
        { id: 'ManagerAssignmentNumber', label: 'Manager assignment number', derive: (c) => (c.job('manager_id') ? assignmentNo(c, c.job('manager_id')) : ''), required: true, ref: 'employee', refValue: (c) => c.job('manager_id') },
        { id: 'PrimaryFlag', label: 'Primary', derive: () => 'Y', required: true },
      ],
      onlyIf: (c) => !!c.job('manager_id'),
    },
    {
      id: 'AssignmentWorkMeasure',
      label: 'FTE',
      stage: 'Employment',
      grain: 'fte',
      datFile: 'Worker.dat',
      component: 'AssignmentWorkMeasure',
      dependsOn: ['Assignment'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('FTE', c), required: true },
        { id: 'AssignmentId(SourceSystemId)', label: 'Assignment', derive: (c) => ssid('ASG', c), required: true },
        { id: 'EffectiveStartDate', label: 'Effective start', derive: (c) => c.latestJobDate, date: true, required: true },
        { id: 'EffectiveEndDate', label: 'Effective end', derive: () => END_OF_TIME, date: true, required: true },
        { id: 'Unit', label: 'Unit', derive: () => 'FTE', required: true },
        { id: 'Value', label: 'Value', derive: (c) => c.job('fte'), required: true },
      ],
    },
    {
      id: 'Salary',
      label: 'Salaries',
      stage: 'Compensation',
      grain: 'comp',
      datFile: 'Salary.dat',
      component: 'Salary',
      dependsOn: ['Assignment'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('SAL', c, `_${(c.effectiveDate || '').replace(/-/g, '')}`), required: true },
        { id: 'AssignmentId(SourceSystemId)', label: 'Assignment', derive: (c) => ssid('ASG', c), required: true },
        { id: 'DateFrom', label: 'Date from', derive: (c) => c.effectiveDate, date: true, required: true },
        { id: 'DateTo', label: 'Date to', derive: (c) => c.endDate, date: true },
        { id: 'SalaryBasisName', label: 'Salary basis', derive: (c) => c.get('pay_component') || c.settings.hdlSalaryBasis, required: true, setting: 'hdlSalaryBasis' },
        { id: 'SalaryAmount', label: 'Salary amount', from: 'salary_amount', required: true },
        { id: 'ActionCode', label: 'Action', derive: (c) => (c.isFirstComp ? c.settings.hdlHireAction : c.settings.hdlSalaryAction), required: true },
      ],
    },
    {
      id: 'WorkRelationshipTermination',
      label: 'Terminations (second load)',
      stage: 'Employment',
      grain: 'termination',
      datFile: 'terminations/Worker.dat',
      component: 'WorkRelationship',
      dependsOn: ['Salary', 'AssignmentWorkMeasure', 'AssignmentSupervisor'],
      fields: [
        owner,
        { id: 'SourceSystemId', label: 'Source system ID', derive: (c) => ssid('WR', c), required: true },
        { id: 'PersonId(SourceSystemId)', label: 'Person', derive: (c) => ssid('PER', c), required: true },
        { id: 'LegalEmployerName', label: 'Legal employer', derive: (c) => legalEmployer(c, 'firstJob'), required: true },
        { id: 'DateStart', label: 'Start date', from: 'hire_date', date: true, required: true },
        { id: 'WorkerType', label: 'Worker type', derive: () => 'E', required: true },
        { id: 'ActualTerminationDate', label: 'Termination date', from: 'termination_date', date: true, required: true },
        { id: 'LastWorkingDate', label: 'Last working date', derive: (c) => c.get('last_day_worked') || c.get('termination_date'), date: true },
        { id: 'TerminateWorkRelationshipFlag', label: 'Terminate', derive: () => 'Y', required: true },
        { id: 'ReasonCode', label: 'Reason', from: 'termination_reason' },
        { id: 'RehireRecommendationFlag', label: 'Rehire recommended', derive: (c) => (/^(y|yes|true|1)$/i.test(c.get('rehire_eligible')) ? 'Y' : c.get('rehire_eligible') ? 'N' : '') },
        { id: 'ActionCode', label: 'Action', derive: (c) => c.settings.hdlTerminationAction, required: true },
      ],
    },
  ],
};
