/**
 * SAP SuccessFactors Employee Central — Core HR import templates.
 *
 * Column IDs follow the standard Employee Central import templates (Import
 * Employee Data / Import Foundation Data). Templates are generated per
 * instance, so customers should compare with the templates downloaded from
 * their own instance; custom fields are added there, not here.
 *
 * Each field takes its value from a canonical concept (`from`) or derives it
 * (`derive(ctx)`). `date: true` fields are written in the chosen date format.
 * `ref` marks a foreign key checked against another file before export.
 * `dependsOn` gives the load order: a file loads only after the files it
 * references exist in SuccessFactors.
 */

const today = () => new Date().toISOString().slice(0, 10);

const foundation = (id, label, list, extra = [], dependsOn = []) => ({
  id,
  label,
  stage: 'Foundation data',
  grain: `org:${list}`,
  dependsOn,
  fields: [
    { id: 'externalCode', label: 'Code', derive: (c) => c.code, required: true },
    { id: 'start-date', label: 'Start Date', derive: (c) => c.settings.foundationStartDate, date: true, required: true },
    { id: 'name', label: 'Name', derive: (c) => c.name || c.code, required: true },
    { id: 'status', label: 'Status', derive: () => 'A', required: true },
    ...extra,
  ],
});

export const SUCCESSFACTORS = {
  id: 'successfactors',
  label: 'SAP SuccessFactors Employee Central',
  entities: [
    foundation('FOCompany', 'Legal Entity', 'company', [
      { id: 'country', label: 'Country', derive: (c) => c.extra.company_country, required: true },
      { id: 'currency', label: 'Default Currency', derive: (c) => c.extra.company_currency },
    ]),
    foundation('FOBusinessUnit', 'Business Unit', 'business_unit'),
    foundation('FODivision', 'Division', 'division'),
    foundation('FOCostCenter', 'Cost Center', 'cost_center', [
      { id: 'legalEntity', label: 'Legal Entity', derive: (c) => c.extra.cost_center_company, ref: 'FOCompany' },
      { id: 'parent', label: 'Parent Cost Center', derive: (c) => c.extra.cost_center_parent, ref: 'FOCostCenter' },
    ], ['FOCompany']),
    foundation('FODepartment', 'Department', 'department', [
      { id: 'cost-center', label: 'Cost Center', derive: (c) => c.extra.cost_center, ref: 'FOCostCenter' },
    ], ['FOCostCenter']),
    foundation('FOLocation', 'Location', 'location', [
      { id: 'timezone', label: 'Time Zone', derive: (c) => c.extra.timezone },
    ]),
    foundation('FOJobCode', 'Job Classification', 'job'),

    {
      id: 'User',
      label: 'Basic User Import',
      stage: 'People',
      grain: 'employee',
      dependsOn: ['FODepartment', 'FOJobCode', 'FODivision', 'FOLocation'],
      fields: [
        { id: 'STATUS', label: 'Status', derive: (c) => c.get('status') || 'active', required: true },
        { id: 'USERID', label: 'User ID', from: 'employee_id', required: true },
        { id: 'USERNAME', label: 'Username', derive: (c) => c.get('username') || c.get('employee_id'), required: true },
        { id: 'FIRSTNAME', label: 'First Name', from: 'first_name', required: true },
        { id: 'LASTNAME', label: 'Last Name', from: 'last_name', required: true },
        { id: 'MI', label: 'Middle Initial', derive: (c) => (c.get('middle_name') || '').slice(0, 1) },
        { id: 'GENDER', label: 'Gender', from: 'gender' },
        { id: 'EMAIL', label: 'Email', from: 'email_work' },
        { id: 'MANAGER', label: 'Manager', derive: (c) => c.job('manager_id') || 'NO_MANAGER', ref: 'employee', required: true },
        { id: 'HR', label: 'HR Rep', derive: () => 'NO_HR', required: true },
        { id: 'DEPARTMENT', label: 'Department', derive: (c) => c.job('department_code'), ref: 'FODepartment' },
        { id: 'JOBCODE', label: 'Job Code', derive: (c) => c.job('job_code'), ref: 'FOJobCode' },
        { id: 'DIVISION', label: 'Division', derive: (c) => c.job('division'), ref: 'FODivision' },
        { id: 'LOCATION', label: 'Location', derive: (c) => c.job('location_code'), ref: 'FOLocation' },
        { id: 'TIMEZONE', label: 'Time Zone', derive: (c) => c.job('timezone') || c.orgExtra('location', c.job('location_code'), 'timezone') || c.settings.defaultTimezone, required: true },
        { id: 'HIREDATE', label: 'Hire Date', from: 'hire_date', date: true },
        { id: 'EMPID', label: 'Employee ID', from: 'employee_id' },
        { id: 'TITLE', label: 'Title', derive: (c) => c.job('job_title') || c.job('job_name') },
      ],
    },
    {
      id: 'PerPerson',
      label: 'Biographical Information',
      stage: 'People',
      grain: 'employee',
      dependsOn: ['User'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'date-of-birth', label: 'Date Of Birth', from: 'date_of_birth', date: true },
        { id: 'country-of-birth', label: 'Country Of Birth', from: 'country_of_birth' },
        { id: 'place-of-birth', label: 'Place Of Birth', from: 'place_of_birth' },
      ],
    },
    {
      id: 'EmpEmployment',
      label: 'Employment Details',
      stage: 'People',
      grain: 'employee',
      dependsOn: ['PerPerson'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'start-date', label: 'Hire Date', from: 'hire_date', date: true, required: true },
        { id: 'originalStartDate', label: 'Original Start Date', derive: (c) => c.get('original_hire_date') || c.get('hire_date'), date: true },
        { id: 'seniorityDate', label: 'Seniority Start Date', derive: (c) => c.get('seniority_date') || c.get('original_hire_date') || c.get('hire_date'), date: true },
      ],
    },
    {
      id: 'PerPersonal',
      label: 'Personal Information',
      stage: 'People',
      grain: 'employee',
      dependsOn: ['PerPerson'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'start-date', label: 'Event Date', from: 'hire_date', date: true, required: true },
        { id: 'first-name', label: 'First Name', from: 'first_name', required: true },
        { id: 'last-name', label: 'Last Name', from: 'last_name', required: true },
        { id: 'middle-name', label: 'Middle Name', from: 'middle_name' },
        { id: 'preferred-name', label: 'Preferred Name', from: 'preferred_name' },
        { id: 'salutation', label: 'Salutation', from: 'salutation' },
        { id: 'gender', label: 'Gender', from: 'gender' },
        { id: 'marital-status', label: 'Marital Status', from: 'marital_status' },
        { id: 'nationality', label: 'Nationality', from: 'nationality' },
      ],
    },
    {
      id: 'EmpJob',
      label: 'Job History',
      stage: 'Employment',
      grain: 'job',
      dependsOn: ['EmpEmployment', 'FOCompany', 'FOCostCenter', 'FOBusinessUnit', 'FODivision', 'FODepartment', 'FOLocation', 'FOJobCode'],
      fields: [
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'start-date', label: 'Event Date', derive: (c) => c.get('job_effective_date') || c.get('hire_date'), date: true, required: true },
        { id: 'seq-number', label: 'Sequence Number', derive: (c) => String(c.seq || 1), required: true },
        { id: 'event-reason', label: 'Event Reason', derive: (c) => c.eventReason, required: true },
        { id: 'company', label: 'Company', from: 'company_code', ref: 'FOCompany', required: true },
        { id: 'business-unit', label: 'Business Unit', from: 'business_unit', ref: 'FOBusinessUnit' },
        { id: 'division', label: 'Division', from: 'division', ref: 'FODivision' },
        { id: 'department', label: 'Department', from: 'department_code', ref: 'FODepartment' },
        { id: 'location', label: 'Location', from: 'location_code', ref: 'FOLocation' },
        { id: 'cost-center', label: 'Cost Center', derive: (c) => c.get('cost_center') || c.orgExtra('department', c.get('department_code'), 'cost_center'), ref: 'FOCostCenter' },
        { id: 'job-code', label: 'Job Classification', from: 'job_code', ref: 'FOJobCode' },
        { id: 'job-title', label: 'Job Title', derive: (c) => c.get('job_title') || c.get('job_name') },
        { id: 'manager-id', label: 'Supervisor', derive: (c) => c.get('manager_id') || 'NO_MANAGER', ref: 'employee' },
        { id: 'employee-class', label: 'Employee Class', from: 'employee_class' },
        { id: 'fte', label: 'FTE', from: 'fte' },
        { id: 'standard-hours', label: 'Standard Weekly Hours', from: 'standard_hours' },
        { id: 'timezone', label: 'Time Zone', derive: (c) => c.get('timezone') || c.orgExtra('location', c.get('location_code'), 'timezone') || c.settings.defaultTimezone },
        { id: 'pay-grade', label: 'Pay Grade', from: 'pay_grade' },
      ],
    },
    {
      id: 'PerEmail',
      label: 'Email Information',
      stage: 'Contact',
      grain: 'email',
      dependsOn: ['PerPerson'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'email-type', label: 'Email Type', derive: (c) => c.emailType, required: true },
        { id: 'email-address', label: 'Email Address', derive: (c) => c.email, required: true },
        { id: 'isPrimary', label: 'Is Primary', derive: (c) => (c.isPrimary ? 'Yes' : 'No'), required: true },
      ],
    },
    {
      id: 'PerPhone',
      label: 'Phone Information',
      stage: 'Contact',
      grain: 'phone',
      dependsOn: ['PerPerson'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'phone-type', label: 'Phone Type', derive: (c) => c.settings.phoneType, required: true },
        { id: 'phone-number', label: 'Phone Number', from: 'phone_work', required: true },
        { id: 'isPrimary', label: 'Is Primary', derive: () => 'Yes', required: true },
      ],
    },
    {
      id: 'PerAddressDEFLT',
      label: 'Addresses',
      stage: 'Contact',
      grain: 'address',
      dependsOn: ['PerPerson'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'effective-start-date', label: 'Event Date', from: 'hire_date', date: true, required: true },
        { id: 'address-type', label: 'Address Type', derive: (c) => c.settings.addressType, required: true },
        { id: 'address1', label: 'Address 1', from: 'address_line1', required: true },
        { id: 'address2', label: 'Address 2', from: 'address_line2' },
        { id: 'city', label: 'City', from: 'city' },
        { id: 'state', label: 'State', from: 'state' },
        { id: 'zip-code', label: 'Postal Code', from: 'postal_code' },
        { id: 'country', label: 'Country', from: 'address_country', required: true },
      ],
    },
    {
      id: 'EmpCompensation',
      label: 'Compensation Information',
      stage: 'Compensation',
      grain: 'compEvent',
      dependsOn: ['EmpJob'],
      fields: [
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'start-date', label: 'Event Date', derive: (c) => c.get('comp_effective_date') || c.get('job_effective_date') || c.get('hire_date'), date: true, required: true },
        { id: 'pay-group', label: 'Pay Group', from: 'pay_group' },
      ],
    },
    {
      id: 'EmpPayCompRecurring',
      label: 'Recurring Pay Components',
      stage: 'Compensation',
      grain: 'comp',
      dependsOn: ['EmpCompensation'],
      fields: [
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'start-date', label: 'Event Date', derive: (c) => c.get('comp_effective_date') || c.get('job_effective_date') || c.get('hire_date'), date: true, required: true },
        { id: 'pay-component', label: 'Pay Component', derive: (c) => c.get('pay_component') || c.settings.basePayComponent, required: true },
        { id: 'paycompvalue', label: 'Amount', from: 'salary_amount', required: true },
        { id: 'currency-code', label: 'Currency', from: 'currency', required: true },
        { id: 'frequency', label: 'Frequency', from: 'pay_frequency', required: true },
      ],
    },
    {
      id: 'EmpPayCompNonRecurring',
      label: 'Non-Recurring Pay Components',
      stage: 'Compensation',
      grain: 'onetime',
      dependsOn: ['EmpJob'],
      fields: [
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'pay-date', label: 'Issue Date', from: 'one_time_date', date: true, required: true },
        { id: 'pay-component-code', label: 'Type', from: 'one_time_component', required: true },
        { id: 'value', label: 'Amount', from: 'one_time_amount', required: true },
        { id: 'currency-code', label: 'Currency', from: 'currency', required: true },
      ],
    },
    {
      id: 'PaymentInformation',
      label: 'Payment Information (bank details)',
      stage: 'Payroll',
      grain: 'bank',
      mdf: true,
      dependsOn: ['EmpJob'],
      fields: [
        { id: 'worker', label: 'Worker', from: 'employee_id', required: true },
        { id: 'effectiveStartDate', label: 'Effective Start Date', from: 'hire_date', date: true, required: true },
        { id: 'paymentMethod', label: 'Payment Method', derive: (c) => c.get('payment_method') || c.settings.paymentMethod, required: true },
        { id: 'bankCountry', label: 'Bank Country', derive: (c) => c.get('bank_country') || c.get('address_country'), required: true },
        { id: 'accountOwner', label: 'Account Owner', derive: (c) => c.get('account_holder') || [c.get('first_name'), c.get('last_name')].filter(Boolean).join(' ') },
        { id: 'iban', label: 'IBAN', from: 'iban', sensitive: true },
        { id: 'accountNumber', label: 'Account Number', from: 'account_number', sensitive: true },
        { id: 'routingNumber', label: 'Routing Number / Sort Code', from: 'bank_routing', sensitive: true },
        { id: 'businessIdentifierCode', label: 'BIC', from: 'bic' },
        { id: 'bank', label: 'Bank', from: 'bank_name' },
      ],
    },
    {
      id: 'PayrollYTD',
      label: 'Payroll YTD Balances (for payroll)',
      stage: 'Payroll',
      grain: 'ytd',
      payroll: true,
      dependsOn: ['User'],
      fields: [
        { id: 'employee-id', label: 'Employee ID', from: 'employee_id', required: true },
        { id: 'company', label: 'Company', derive: (c) => c.job('company_code'), ref: 'FOCompany' },
        { id: 'tax-year', label: 'Tax Year', from: 'tax_year', required: true },
        { id: 'wage-type', label: 'Wage Type', from: 'wage_type', required: true },
        { id: 'amount', label: 'Amount', from: 'ytd_amount', required: true },
        { id: 'currency', label: 'Currency', from: 'currency', required: true },
      ],
    },
    {
      id: 'EmpEmploymentTermination',
      label: 'Termination Details',
      stage: 'Employment',
      grain: 'termination',
      dependsOn: ['EmpJob'],
      fields: [
        { id: 'person-id-external', label: 'Person ID', from: 'employee_id', required: true },
        { id: 'user-id', label: 'User ID', from: 'employee_id', required: true },
        { id: 'end-date', label: 'Termination Date', from: 'termination_date', date: true, required: true },
        { id: 'event-reason', label: 'Event Reason', from: 'termination_reason', required: true },
        { id: 'last-date-worked', label: 'Last Date Worked', derive: (c) => c.get('last_day_worked') || c.get('termination_date'), date: true },
        { id: 'ok-to-rehire', label: 'OK To Rehire', from: 'rehire_eligible' },
      ],
    },
  ],
};

export const DEFAULT_SETTINGS = {
  dateFormat: 'MM/dd/yyyy',
  sourceDateOrder: 'auto',
  foundationStartDate: '1900-01-01',
  hireEventReason: 'HIRNEW',
  jobChangeEventReason: 'JOBCHG',
  transferEventReason: 'TRANSFER',
  changeEventReason: 'DATACHG',
  paymentMethod: 'BANK_TRANSFER',
  defaultTimezone: 'Europe/London',
  phoneType: 'B',
  addressType: 'home',
  workEmailType: 'B',
  personalEmailType: 'P',
  basePayComponent: 'BASE',
  labelRow: true,
  asOf: today(),
};
