"""Build the showcase sample pack in public/sample-data/.

Every company, person and number is fictional and generated from a fixed seed, so the files and
the expected results in public/sample-data/expected.json are the same on every run. The expected
results are computed here with pandas and checked against the Workbench code in
src/lib/showcase.test.js and against the server in backend/tests/test_showcase_pack.py, so the
demo script never promises a number the product does not show.

Run from the repo root:  python scripts/build_showcase.py
"""
from __future__ import annotations

import json
import random
from datetime import date, timedelta
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

OUT = Path(__file__).resolve().parent.parent / "public" / "sample-data"
NAVY = "0F1B2D"
HEAD_FILL = PatternFill("solid", fgColor=NAVY)
HEAD_FONT = Font(bold=True, color="FFFFFF")
TITLE_FONT = Font(bold=True, size=14, color=NAVY)
NOTE_FONT = Font(italic=True, color="64748B")
GBP = '"£"#,##0;[Red]-"£"#,##0'
GBP2 = '"£"#,##0.00;[Red]-"£"#,##0.00'
ACTIVITIES = ["Drafting", "Meetings", "Court and hearings", "Research", "Calls and email", "Admin", "Business development"]
NON_BILLABLE = {"Admin", "Business development"}
MONTHS_FY = ["Apr-26", "May-26", "Jun-26", "Jul-26", "Aug-26", "Sep-26"]


def month_starts(first: date, n: int) -> list[date]:
    out, y, m = [], first.year, first.month
    for _ in range(n):
        out.append(date(y, m, 1))
        m += 1
        if m == 13:
            y, m = y + 1, 1
    return out


def rand_day(r: random.Random, month: date) -> date:
    return month + timedelta(days=r.randint(0, 27))


def write_table(ws, columns, rows, start_row=1, formats=None, widths=None):
    """A styled table: navy header, frozen header row, number formats and column widths."""
    formats = formats or {}
    for j, name in enumerate(columns, 1):
        c = ws.cell(row=start_row, column=j, value=name)
        c.fill, c.font = HEAD_FILL, HEAD_FONT
        c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    for i, row in enumerate(rows, start_row + 1):
        for j, v in enumerate(row, 1):
            c = ws.cell(row=i, column=j, value=v)
            fmt = formats.get(columns[j - 1])
            if fmt:
                c.number_format = fmt
            elif isinstance(v, date):
                c.number_format = "dd/mm/yyyy"
    ws.freeze_panes = ws.cell(row=start_row + 1, column=1)
    for j, name in enumerate(columns, 1):
        width = (widths or {}).get(name) or max(12, min(34, len(str(name)) + 4))
        ws.column_dimensions[get_column_letter(j)].width = width


def title_block(ws, title, subtitle):
    ws["A1"] = title
    ws["A1"].font = TITLE_FONT
    ws["A2"] = subtitle
    ws["A2"].font = NOTE_FONT
    return 4  # the table starts after a blank row


def readme_tab(wb, title, lines):
    ws = wb.active
    ws.title = "Read me"
    ws["A1"] = title
    ws["A1"].font = TITLE_FONT
    for i, line in enumerate(lines, 3):
        ws.cell(row=i, column=1, value=line)
    ws["A{}".format(len(lines) + 4)] = "Fictional sample data generated by meldra for demonstrations. Any resemblance to real organisations or people is coincidental."
    ws["A{}".format(len(lines) + 4)].font = NOTE_FONT
    ws.column_dimensions["A"].width = 120


def statement(wb, name, title, subtitle, items, periods, fmt=GBP):
    """Items down the side, periods across the top (P&L layout), under a title block."""
    ws = wb.create_sheet(name)
    start = title_block(ws, title, subtitle)
    cols = ["Line item", *periods]
    write_table(ws, cols, [[k, *v] for k, v in items], start_row=start, formats={p: fmt for p in periods}, widths={"Line item": 32})
    for i, (k, _) in enumerate(items, start + 1):
        if k in {"Gross profit", "EBITDA", "Net profit", "Operating profit", "Total income", "Total costs", "Surplus"}:
            for j in range(1, len(cols) + 1):
                ws.cell(row=i, column=j).font = Font(bold=True)
    return ws


def frame(columns, rows):
    return pd.DataFrame(rows, columns=columns)


def gbp(n):
    return round(float(n), 2)


# ---------------------------------------------------------------------------------------------
# 1. Law firm: time, matters, management accounts, aged debt
# ---------------------------------------------------------------------------------------------
def law_firm():
    r = random.Random(101)
    grades = {"Partner": (395, 4.6), "Senior Associate": (310, 5.6), "Associate": (245, 6.0), "Trainee": (160, 5.4), "Paralegal": (125, 5.8)}
    people = [
        ("Eleanor Hartwell", "Partner"), ("Marcus Lane", "Partner"), ("Priya Raman", "Partner"),
        ("Tom Ashby", "Senior Associate"), ("Grace Okafor", "Senior Associate"), ("Daniel Moretti", "Senior Associate"),
        ("Hannah Cole", "Associate"), ("Yusuf Malik", "Associate"), ("Sophie Wren", "Associate"), ("Liam Doyle", "Associate"),
        ("Aisha Begum", "Trainee"), ("Oliver Grant", "Trainee"), ("Chloe Fenn", "Paralegal"), ("Ravi Shah", "Paralegal"),
    ]
    areas = ["Corporate", "Litigation", "Employment", "Real Estate", "Private Client"]
    clients = ["Brightwater Foods", "Calder Logistics", "Fenwick Estates", "Harbour Dental Group", "Kestrel Software",
               "Linden Care Homes", "Marlow Engineering", "Northgate Retail", "Oakridge Academy Trust", "Pemberton Family",
               "Quayside Hotels", "Redfern Pharma", "Silverline Haulage", "Thornbury Farms", "Vale Credit Union"]
    partners = {"Corporate": "Eleanor Hartwell", "Litigation": "Marcus Lane", "Employment": "Priya Raman",
                "Real Estate": "Eleanor Hartwell", "Private Client": "Priya Raman"}
    fee_types = {"Corporate": "Hourly", "Litigation": "Hourly", "Employment": "Capped", "Real Estate": "Fixed", "Private Client": "Fixed"}

    matters = []
    for i in range(1, 37):
        area = areas[(i - 1) % 5] if i <= 30 else r.choice(areas)
        client = clients[(i * 7) % len(clients)]
        opened = date(2026, 1, 1) + timedelta(days=r.randint(0, 200))
        matters.append({"Matter ID": f"HL-{2600 + i}", "Client": client, "Practice area": area, "Partner": partners[area],
                        "Opened": opened, "Fee type": fee_types[area]})

    months = month_starts(date(2026, 4, 1), 6)
    time_rows = []
    for name, grade in people:
        rate, daily = grades[grade]
        home = r.sample(areas, 2)
        for m in months:
            for _ in range(r.randint(55, 63)):  # about three entries a working day
                matter = r.choice([x for x in matters if x["Practice area"] in home] or matters)
                hours = round(max(0.5, r.gauss(daily / 3, 0.6)) * 2) / 2
                activity = r.choices(ACTIVITIES, weights=[30, 18, 10, 16, 12, 8 if grade != "Partner" else 14, 6 if grade != "Partner" else 12])[0]
                billable = activity not in NON_BILLABLE
                time_rows.append([rand_day(r, m), name, matter["Practice area"], grade, matter["Matter ID"], matter["Client"],
                                  activity, hours, rate, round(hours * rate, 2) if billable else 0.0])
    # The clean samples have no exact duplicates (two identical entries on the same day); the
    # complex/messy pack is where duplicates are planted.
    time_rows = [list(t) for t in dict.fromkeys(tuple(row) for row in time_rows)]
    time_rows.sort(key=lambda x: (x[0], x[1]))
    # Workbench charts the first number column by the category with the fewest values, so Practice area
    # comes before Grade (both have five) and Hours is the first number.
    time_cols = ["Date", "Fee earner", "Practice area", "Grade", "Matter ID", "Client", "Activity", "Hours", "Rate", "Value"]
    t = frame(time_cols, time_rows)

    # Matters: billing outcome per matter from the recorded time
    by_matter = t.groupby("Matter ID")["Value"].sum()
    mat_rows = []
    for m in matters:
        wip = gbp(by_matter.get(m["Matter ID"], 0.0))
        real = {"Corporate": 0.93, "Litigation": 0.86, "Employment": 0.81, "Real Estate": 0.77, "Private Client": 0.9}[m["Practice area"]]
        billed = gbp(wip * real * r.uniform(0.92, 1.02))
        collected = gbp(billed * r.uniform(0.62, 0.98))
        mat_rows.append([m["Matter ID"], m["Client"], m["Practice area"], m["Partner"], m["Opened"], m["Fee type"],
                         wip, billed, collected, gbp(billed - collected)])
    mat_cols = ["Matter ID", "Client", "Practice area", "Partner", "Opened", "Fee type", "Time value", "Billed", "Collected", "Unpaid"]
    mt = frame(mat_cols, mat_rows)

    fee = [gbp(t[pd.to_datetime(t["Date"]).dt.month == mo.month]["Value"].sum() * 0.87) for mo in months]
    disb = [gbp(x * 0.04) for x in fee]
    salaries = [gbp(r.uniform(128000, 132000)) for _ in months]
    rent = [32500.0] * 6
    pii = [9800.0] * 6
    it = [gbp(r.uniform(11000, 14500)) for _ in months]
    mkt = [gbp(r.uniform(4000, 9000)) for _ in months]
    total_income = [gbp(a + b) for a, b in zip(fee, disb)]
    total_costs = [gbp(sum(x)) for x in zip(salaries, rent, pii, it, mkt)]
    net = [gbp(a - b) for a, b in zip(total_income, total_costs)]
    pl = [("Fee income", fee), ("Disbursements recovered", disb), ("Total income", total_income),
          ("Salaries", salaries), ("Rent and rates", rent), ("Professional indemnity", pii),
          ("IT and case management", it), ("Marketing", mkt), ("Total costs", total_costs), ("Net profit", net)]

    # Aged debt splits each client's unpaid bills (from Matters) by age, so the two tabs agree.
    unpaid_by_client = mt.groupby("Client")["Unpaid"].sum()
    debt_rows = []
    for c in clients:
        owed = gbp(unpaid_by_client.get(c, 0.0))
        w = [0.05, 0.1, 0.15, 0.7] if c in ("Northgate Retail", "Silverline Haulage") else [r.uniform(0.3, 0.6), r.uniform(0.15, 0.3), r.uniform(0.05, 0.15), r.uniform(0, 0.1)]
        b = [gbp(owed * x / sum(w)) for x in w[:3]]
        b.append(gbp(owed - sum(b)))
        debt_rows.append([c, owed, *b])
    debt_rows.sort(key=lambda x: -x[1])
    debt_cols = ["Client", "Owed", "0-30 days", "31-60 days", "61-90 days", "Over 90 days"]

    wb = Workbook()
    readme_tab(wb, "Hartwell & Lane LLP: practice data, April to September 2026", [
        "Time entries: every recorded hour, by fee earner, grade, practice area and matter.",
        "Matters: time value, billed, collected and unpaid per matter.",
        "Management accounts: a monthly P&L with a title block above the table, as practice systems export it.",
        "Aged debt: what each client owes, by age.",
    ])
    ws = wb.create_sheet("Time entries")
    write_table(ws, time_cols, time_rows, formats={"Rate": GBP, "Value": GBP2}, widths={"Fee earner": 20, "Client": 24})
    ws = wb.create_sheet("Matters")
    write_table(ws, mat_cols, mat_rows, formats={k: GBP for k in ["Time value", "Billed", "Collected", "Unpaid"]}, widths={"Client": 24, "Partner": 20})
    statement(wb, "Management accounts", "Hartwell & Lane LLP: management accounts", "Monthly, £. Unaudited.", pl, MONTHS_FY)
    ws = wb.create_sheet("Aged debt")
    write_table(ws, debt_cols, debt_rows, formats={k: GBP for k in debt_cols[1:]}, widths={"Client": 24})
    wb.save(OUT / "law-firm-hartwell-lane.xlsx")

    bill = t[~t["Activity"].isin(NON_BILLABLE)]
    expected = {
        "time_entries_rows": len(t),
        "value_by_practice_area": {k: gbp(v) for k, v in t.groupby("Practice area")["Value"].sum().items()},
        "billable_hours_share": round(bill["Hours"].sum() / t["Hours"].sum() * 100, 1),
        "realisation_by_practice_area": {k: round(g["Billed"].sum() / g["Time value"].sum() * 100, 1) for k, g in mt.groupby("Practice area")},
        "unpaid_total": gbp(mt["Unpaid"].sum()),
        "over_90_days_total": gbp(sum(row[5] for row in debt_rows)),
        "net_profit_by_month": dict(zip(MONTHS_FY, net)),
    }
    return expected


# ---------------------------------------------------------------------------------------------
# 2. Finance: multi-entity group, P&L, budget vs actual, revenue by customer
# ---------------------------------------------------------------------------------------------
def finance():
    r = random.Random(202)
    months = month_starts(date(2025, 10, 1), 12)
    labels = [m.strftime("%b-%y") for m in months]
    season = [0.92, 0.95, 1.08, 0.86, 0.9, 1.02, 0.98, 1.0, 1.04, 1.06, 0.97, 1.12]
    rev = [gbp(1_850_000 * s * (1 + i * 0.012) * r.uniform(0.98, 1.02)) for i, s in enumerate(season)]
    cogs = [gbp(x * r.uniform(0.54, 0.57)) for x in rev]
    gp = [gbp(a - b) for a, b in zip(rev, cogs)]
    staff = [gbp(r.uniform(318000, 334000) * (1 + i * 0.004)) for i in range(12)]
    prem = [gbp(r.uniform(88000, 92000)) for _ in range(12)]
    mkt = [gbp(r.uniform(42000, 76000)) for _ in range(12)]
    other = [gbp(r.uniform(51000, 63000)) for _ in range(12)]
    ebitda = [gbp(g - sum(x)) for g, *x in zip(gp, staff, prem, mkt, other)]
    pl = [("Revenue", rev), ("Cost of sales", cogs), ("Gross profit", gp), ("Staff costs", staff), ("Premises", prem),
          ("Marketing", mkt), ("Other overheads", other), ("EBITDA", ebitda)]

    depts = {"Sales": 61000, "Marketing": 52000, "Operations": 88000, "Technology": 74000, "Finance": 38000, "People": 29000}
    bva = []
    for m, lab in zip(months, labels):
        for d, base in depts.items():
            budget = gbp(base * (1 + 0.01 * months.index(m)))
            drift = 1.14 if d == "Technology" and m.month in (3, 4, 5, 6) else 1.0
            actual = gbp(budget * r.uniform(0.9, 1.08) * drift)
            bva.append([m, d, budget, actual, gbp(actual - budget)])
    bva_cols = ["Month", "Department", "Budget", "Actual", "Variance"]

    customers = {"Aldermoor Health": ("UK & Ireland", 1.4), "Brennan Mills": ("UK & Ireland", 0.9), "Castellan Bank": ("Europe", 1.6),
                 "Dovetail Retail": ("UK & Ireland", 1.1), "Everly Telecom": ("Europe", 1.3), "Fairhaven Council": ("UK & Ireland", 0.6),
                 "Greystone Energy": ("North America", 1.5), "Holloway Insurance": ("Europe", 0.8), "Ivory Coast Shipping": ("North America", 0.7),
                 "Juniper Education": ("UK & Ireland", 0.5)}
    lines = ["Software", "Support", "Services"]
    sales = []
    n = 0
    for m in months:
        for cust, (region, size) in customers.items():
            for line in lines:
                if r.random() < 0.55:
                    n += 1
                    amount = gbp(r.uniform(6000, 32000) * size * {"Software": 1.4, "Support": 0.6, "Services": 1.0}[line])
                    sales.append([f"INV-{50000 + n}", rand_day(r, m), cust, region, line, amount])
    sales_cols = ["Invoice", "Invoice date", "Customer", "Region", "Product line", "Amount"]

    wb = Workbook()
    readme_tab(wb, "Northbridge Group plc: finance pack, October 2025 to September 2026", [
        "Group P&L: twelve months of revenue, costs and EBITDA in statement layout (line items down, months across).",
        "Budget vs actual: monthly spend by department, with a deliberate overspend in Technology from March to June.",
        "Key account invoices: every invoice to the ten key accounts (about 15% of revenue), by region and product line.",
        "The intercompany case is in complex/intercompany-uk.xlsx and complex/intercompany-de.xlsx.",
    ])
    statement(wb, "Group P&L", "Northbridge Group plc: consolidated P&L", "Monthly, £. Management accounts, unaudited.", pl, labels)
    ws = wb.create_sheet("Budget vs actual")
    write_table(ws, bva_cols, bva, formats={"Budget": GBP, "Actual": GBP, "Variance": GBP})
    ws = wb.create_sheet("Key account invoices")
    write_table(ws, sales_cols, sales, formats={"Amount": GBP2}, widths={"Customer": 24, "Region": 18})
    wb.save(OUT / "finance-northbridge-group.xlsx")

    b = frame(bva_cols, bva)
    s = frame(sales_cols, sales)
    return {
        "revenue_total": gbp(sum(rev)),
        "ebitda_total": gbp(sum(ebitda)),
        "ebitda_margin": round(sum(ebitda) / sum(rev) * 100, 1),
        "budget_by_department": {k: gbp(v) for k, v in b.groupby("Department")["Budget"].sum().items()},
        "variance_by_department": {k: gbp(v) for k, v in b.groupby("Department")["Variance"].sum().items()},
        "sales_by_region": {k: gbp(v) for k, v in s.groupby("Region")["Amount"].sum().items()},
        "sales_invoices_rows": len(s),
    }


# ---------------------------------------------------------------------------------------------
# 3. University: enrolment trend, students, survey, research income
# ---------------------------------------------------------------------------------------------
def university():
    r = random.Random(303)
    faculties = {"Business": 3200, "Engineering": 2600, "Health Sciences": 2900, "Arts & Humanities": 1700, "Computing": 2100, "Law": 1100}
    years = ["2021/22", "2022/23", "2023/24", "2024/25", "2025/26"]
    trend = {"Business": [1, 1.05, 1.08, 1.02, 0.97], "Engineering": [1, 1.02, 1.04, 1.07, 1.1], "Health Sciences": [1, 1.06, 1.1, 1.15, 1.18],
             "Arts & Humanities": [1, 0.96, 0.91, 0.86, 0.8], "Computing": [1, 1.12, 1.25, 1.33, 1.41], "Law": [1, 1.0, 1.02, 1.01, 1.03]}
    # Year labels like 2021/22 are not recognised as periods, so the enrolment tab uses year columns "2022" etc.
    ycols = ["2022", "2023", "2024", "2025", "2026"]
    enrol = [(f, [int(base * m * r.uniform(0.99, 1.01)) for m in trend[f]]) for f, base in faculties.items()]

    programmes = {"Business": ["BA Accounting", "BSc Management", "MBA"], "Engineering": ["BEng Mechanical", "BEng Civil", "MEng Electrical"],
                  "Health Sciences": ["BSc Nursing", "BSc Physiotherapy", "MSc Public Health"], "Arts & Humanities": ["BA History", "BA English", "BA Fine Art"],
                  "Computing": ["BSc Computer Science", "BSc Data Science", "MSc AI"], "Law": ["LLB Law", "LLM International Law"]}
    students = []
    for i in range(1, 901):
        fac = r.choices(list(faculties), weights=list(faculties.values()))[0]
        prog = r.choice(programmes[fac])
        fee = "International" if r.random() < (0.38 if fac in ("Business", "Computing") else 0.18) else "Home"
        fac_att = {"Business": 84, "Engineering": 88, "Health Sciences": 92, "Arts & Humanities": 78, "Computing": 83, "Law": 87}[fac]
        attendance = max(35, min(100, round(r.gauss(fac_att + (3 if fee == "International" else 0), 9))))
        avg = max(28, min(92, round(r.gauss(61, 10) + (attendance - 85) * 0.35, 1)))
        withdraw_p = 0.03 + (0.16 if attendance < 70 else 0) + (0.05 if fac == "Arts & Humanities" else 0)
        cont = "Withdrawn" if r.random() < withdraw_p else "Continued"
        students.append([f"S{240000 + i}", fac, prog, r.choice([1, 2, 3]), fee, attendance, avg, cont])
    stu_cols = ["Student ID", "Faculty", "Programme", "Year of study", "Fee status", "Attendance %", "Module average", "Continuation"]

    themes = ["Teaching", "Assessment and feedback", "Academic support", "Organisation", "Learning resources", "Student voice"]
    nss = [[f, th, round(min(97, max(55, r.gauss(79, 6))), 1)] for f in faculties for th in themes]
    nss_cols = ["Faculty", "Theme", "Agree score"]

    funders = ["UKRI", "Wellcome Trust", "Industry", "EU Horizon", "Charities"]
    research = []
    for f in faculties:
        for y in ycols:
            for fu in funders:
                if r.random() < 0.6:
                    research.append([f, fu, y, gbp(r.uniform(40000, 900000) * (1.8 if f in ("Engineering", "Health Sciences") else 0.7))])
    res_cols = ["Faculty", "Funder", "Year", "Income"]

    wb = Workbook()
    readme_tab(wb, "Ashford University: planning data", [
        "Enrolment: headcount by faculty over five academic years (years across the top; 2026 means 2025/26).",
        "Students: one row per student with attendance, module average and whether they continued.",
        "Student survey: agreement scores by faculty and theme (averaged, not added up).",
        "Research income: by faculty, funder and year.",
    ])
    statement(wb, "Enrolment", "Ashford University: enrolment by faculty", "Headcount at 1 December; 2026 = academic year 2025/26.", enrol, ycols, fmt="#,##0")
    ws = wb.create_sheet("Students")
    write_table(ws, stu_cols, students, widths={"Programme": 24})
    ws = wb.create_sheet("Student survey")
    write_table(ws, nss_cols, nss, widths={"Theme": 26})
    ws = wb.create_sheet("Research income")
    write_table(ws, res_cols, research, formats={"Income": GBP})
    wb.save(OUT / "university-ashford.xlsx")

    st = frame(stu_cols, students)
    low = st[st["Attendance %"] < 70]
    return {
        "students_rows": len(st),
        "average_attendance_by_faculty": {k: round(v, 2) for k, v in st.groupby("Faculty")["Attendance %"].mean().items()},
        "withdrawal_rate": round((st["Continuation"] == "Withdrawn").mean() * 100, 1),
        "withdrawal_rate_low_attendance": round((low["Continuation"] == "Withdrawn").mean() * 100, 1),
        "enrolment_2026": {f: v[-1] for f, v in enrol},
        "average_agree_by_faculty": {k: round(v, 2) for k, v in frame(nss_cols, nss).groupby("Faculty")["Agree score"].mean().items()},
    }


# ---------------------------------------------------------------------------------------------
# 4. Insurance: claims bordereau and premiums
# ---------------------------------------------------------------------------------------------
def insurance():
    r = random.Random(404)
    lobs = {"Motor": (5200, 0.62), "Property": (14800, 0.55), "Liability": (22500, 0.48), "Marine": (31000, 0.71)}
    regions = ["London", "South East", "Midlands", "North", "Scotland"]
    causes = {"Motor": ["Collision", "Theft", "Windscreen"], "Property": ["Escape of water", "Fire", "Storm", "Theft"],
              "Liability": ["Slip or trip", "Product fault", "Professional error"], "Marine": ["Cargo damage", "Hull damage", "Delay"]}
    months = month_starts(date(2025, 10, 1), 12)
    claims = []
    for i in range(1, 641):
        lob = r.choices(list(lobs), weights=[45, 30, 17, 8])[0]
        sev, _ = lobs[lob]
        loss = rand_day(r, r.choice(months))
        notified = loss + timedelta(days=int(abs(r.gauss(9, 8))))
        incurred = gbp(abs(r.lognormvariate(0, 0.9)) * sev)
        status = r.choices(["Closed", "Open", "Reopened"], weights=[58, 37, 5])[0]
        paid = incurred if status == "Closed" else gbp(incurred * r.uniform(0, 0.6))
        claims.append([f"CLM-{70000 + i}", f"POL-{r.randint(100000, 199999)}", lob, r.choice(regions), r.choice(causes[lob]),
                       loss, notified, status, paid, gbp(incurred - paid), incurred])
    claim_cols = ["Claim ID", "Policy ID", "Line of business", "Region", "Cause", "Loss date", "Notified date", "Status", "Paid", "Reserve", "Incurred"]
    # Incurred is the measure people chart, so it is the first number column: move it before Paid.
    order = [0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9]
    claim_cols = [claim_cols[i] for i in order]
    claims = [[row[i] for i in order] for row in claims]

    cl = frame(claim_cols, claims)
    prem = []
    for m in months:
        for lob in lobs:
            inc = cl[(pd.to_datetime(cl["Loss date"]).dt.month == m.month) & (cl["Line of business"] == lob)]["Incurred"].sum()
            earned = gbp(inc / lobs[lob][1] * r.uniform(0.94, 1.06)) if inc else gbp(r.uniform(40000, 90000))
            prem.append([m, lob, gbp(earned * r.uniform(1.0, 1.12)), earned])
    prem_cols = ["Month", "Line of business", "Written premium", "Earned premium"]

    wb = Workbook()
    readme_tab(wb, "Kingsmere Underwriting: claims bordereau, October 2025 to September 2026", [
        "Claims: one row per claim with paid, reserve and incurred.",
        "Premiums: written and earned premium by month and line of business.",
        "Loss ratio = incurred claims / earned premium. Marine runs hottest on purpose.",
    ])
    ws = wb.create_sheet("Claims")
    write_table(ws, claim_cols, claims, formats={k: GBP2 for k in ["Paid", "Reserve", "Incurred"]}, widths={"Cause": 18, "Line of business": 16})
    ws = wb.create_sheet("Premiums")
    write_table(ws, prem_cols, prem, formats={"Written premium": GBP, "Earned premium": GBP})
    wb.save(OUT / "insurance-kingsmere-claims.xlsx")

    p = frame(prem_cols, prem)
    lr = {lob: round(cl[cl["Line of business"] == lob]["Incurred"].sum() / p[p["Line of business"] == lob]["Earned premium"].sum() * 100, 1) for lob in lobs}
    return {
        "claims_rows": len(cl),
        "incurred_by_line": {k: gbp(v) for k, v in cl.groupby("Line of business")["Incurred"].sum().items()},
        "loss_ratio_by_line": lr,
        "open_reserve_total": gbp(cl[cl["Status"] != "Closed"]["Reserve"].sum()),
    }


# ---------------------------------------------------------------------------------------------
# 5. Manufacturing: production, scrap, downtime, inventory
# ---------------------------------------------------------------------------------------------
def manufacturing():
    r = random.Random(505)
    lines = {"Line A": 1.0, "Line B": 0.92, "Line C": 1.08, "Line D": 0.75}
    products = ["Valve body", "Pump housing", "Bracket", "Gear blank"]
    days = [date(2026, 7, 1) + timedelta(days=i) for i in range(92) if (date(2026, 7, 1) + timedelta(days=i)).weekday() < 5]
    prod = []
    for d in days:
        for line, eff in lines.items():
            for shift in ("Early", "Late"):
                planned = 480
                down = int(abs(r.gauss(28 if line != "Line D" else 64, 18)))
                units = int((planned - down) / 0.9 * eff * r.uniform(0.95, 1.03))
                scrap_rate = (0.018 if line != "Line C" else 0.041) * r.uniform(0.6, 1.4)
                prod.append([d, line, shift, r.choice(products), units, int(units * scrap_rate), down])
    prod_cols = ["Date", "Line", "Shift", "Product", "Units produced", "Units scrapped", "Downtime minutes"]

    inv = []
    cats = {"Raw material": 12, "Component": 18, "Consumable": 8, "Finished good": 10}
    k = 0
    for cat, n in cats.items():
        for _ in range(n):
            k += 1
            on_hand = r.randint(0, 2400)
            reorder = r.randint(150, 900)
            inv.append([f"SKU-{3000 + k}", f"{cat} {k:02d}", cat, on_hand, reorder, gbp(r.uniform(0.4, 85)),
                        "Reorder now" if on_hand < reorder else "OK"])
    inv_cols = ["SKU", "Description", "Category", "On hand", "Reorder point", "Unit cost", "Stock status"]

    oee_months = ["Jul-26", "Aug-26", "Sep-26"]
    oee = [(line, [round(r.uniform(0.68, 0.84) * (0.88 if line == "Line D" else 1) * 100, 1) for _ in oee_months]) for line in lines]

    wb = Workbook()
    readme_tab(wb, "Corran Precision Ltd: plant data, July to September 2026", [
        "Production: units, scrap and downtime per line and shift for every working day.",
        "Inventory: stock on hand against reorder points.",
        "OEE: overall equipment effectiveness by line and month, in %.",
        "Line C scraps the most; Line D loses the most time to downtime.",
    ])
    ws = wb.create_sheet("Production")
    write_table(ws, prod_cols, prod, formats={"Units produced": "#,##0", "Units scrapped": "#,##0"})
    ws = wb.create_sheet("Inventory")
    write_table(ws, inv_cols, inv, formats={"Unit cost": GBP2})
    statement(wb, "OEE", "Corran Precision Ltd: OEE by line", "Monthly, %.", oee, oee_months, fmt="0.0")
    wb.save(OUT / "manufacturing-corran-precision.xlsx")

    pr = frame(prod_cols, prod)
    g = pr.groupby("Line")
    return {
        "production_rows": len(pr),
        "units_by_line": {k: int(v) for k, v in g["Units produced"].sum().items()},
        "scrap_rate_by_line": {k: round(x["Units scrapped"].sum() / x["Units produced"].sum() * 100, 2) for k, x in g},
        "downtime_by_line": {k: int(v) for k, v in g["Downtime minutes"].sum().items()},
        "skus_to_reorder": sum(1 for row in inv if row[6] == "Reorder now"),
    }


# ---------------------------------------------------------------------------------------------
# 6. HR and payroll: headcount, payroll by month
# ---------------------------------------------------------------------------------------------
def hr():
    r = random.Random(606)
    depts = {"Engineering": (64000, 38), "Sales": (52000, 26), "Customer Success": (41000, 22), "Finance": (55000, 12), "People": (47000, 9), "Operations": (44000, 18)}
    locs = ["London", "Manchester", "Edinburgh", "Remote"]
    first = ["Ava", "Ben", "Cara", "Dev", "Ella", "Femi", "Gus", "Hana", "Ibrahim", "Jade", "Kai", "Lena", "Max", "Nia", "Owen", "Pia", "Rory", "Sana", "Theo", "Uma", "Vik", "Wren", "Zara"]
    last = ["Adams", "Bose", "Clarke", "Dunn", "Evans", "Fraser", "Gill", "Hughes", "Iqbal", "Jones", "Kaur", "Lewis", "Mensah", "Nash", "Owens", "Price", "Reid", "Singh", "Turner", "Webb"]
    emps = []
    n = 0
    for dept, (base, count) in depts.items():
        for _ in range(count):
            n += 1
            start = date(2017, 1, 1) + timedelta(days=r.randint(0, 3500))
            grade = r.choices(["G2", "G3", "G4", "G5", "G6"], weights=[20, 34, 26, 14, 6])[0]
            sal = gbp(base * {"G2": 0.72, "G3": 0.9, "G4": 1.1, "G5": 1.4, "G6": 1.85}[grade] * r.uniform(0.94, 1.08))
            status = "Leaver" if r.random() < 0.12 else "Active"
            emps.append([f"E{1000 + n}", f"{r.choice(first)} {r.choice(last)}", dept, r.choice(locs), grade, start, sal, status])
    emp_cols = ["Employee ID", "Name", "Department", "Location", "Grade", "Start date", "Salary", "Status"]

    months = month_starts(date(2026, 4, 1), 6)
    payroll = []
    active = [e for e in emps if e[7] == "Active"]
    for m in months:
        for dept in depts:
            staff = [e for e in active if e[2] == dept]
            gross = gbp(sum(e[6] for e in staff) / 12 * r.uniform(1.0, 1.03))
            payroll.append([m, dept, len(staff), gross, gbp(gross * 0.138), gbp(gross * 0.05)])
    pay_cols = ["Pay month", "Department", "Headcount", "Gross pay", "Employer NI", "Employer pension"]
    # Gross pay should drive the default chart, not Headcount.
    pay_cols = ["Pay month", "Department", "Gross pay", "Employer NI", "Employer pension", "Headcount"]
    payroll = [[p[0], p[1], p[3], p[4], p[5], p[2]] for p in payroll]

    wb = Workbook()
    readme_tab(wb, "Fernhill Systems Ltd: people data", [
        "Employees: one row per person with department, location, grade, salary and status.",
        "Payroll: monthly gross pay, employer NI and pension by department.",
        "For an HR system migration demo, use Migration > Try a sample system extract (a deliberately messy Workday-style file).",
    ])
    ws = wb.create_sheet("Employees")
    write_table(ws, emp_cols, emps, formats={"Salary": GBP}, widths={"Name": 20, "Department": 18})
    ws = wb.create_sheet("Payroll")
    write_table(ws, pay_cols, payroll, formats={k: GBP for k in ["Gross pay", "Employer NI", "Employer pension"]}, widths={"Department": 18})
    wb.save(OUT / "hr-fernhill-people.xlsx")

    e = frame(emp_cols, emps)
    return {
        "employees_rows": len(e),
        "salary_by_department": {k: gbp(v) for k, v in e.groupby("Department")["Salary"].sum().items()},
        "active_headcount": int((e["Status"] == "Active").sum()),
        "gross_pay_total": gbp(sum(p[2] for p in payroll)),
    }


# ---------------------------------------------------------------------------------------------
# Complex cases
# ---------------------------------------------------------------------------------------------
def messy_pack():
    """The kind of workbook that breaks macros: cover tab, empty tab, titles, text numbers, mixed dates, duplicates."""
    r = random.Random(707)
    wb = Workbook()
    ws = wb.active
    ws.title = "Cover"
    ws["B3"] = "Q3 MANAGEMENT PACK"
    ws["B3"].font = Font(bold=True, size=20, color=NAVY)
    ws["B5"] = "Prepared by Finance. Draft, not for circulation."
    wb.create_sheet("Notes (blank)")

    ws = wb.create_sheet("Regional sales")
    ws["A1"] = "Regional sales, Q3 2026"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = "Source: three regional spreadsheets pasted together. Amounts as typed by each region."
    ws["A2"].font = NOTE_FONT
    cols = ["Order date", "Region", "Rep", "Customer", "Amount", "Discount %"]
    regions = {"North": "dd/mm/yyyy text", "South": "real dates", "West": "ISO text"}
    reps = {"North": ["Amy", "Bilal"], "South": ["Carys", "Dan"], "West": ["Eve", "Farid"]}
    rows = []
    for i in range(150):
        reg = list(regions)[i % 3]
        d = date(2026, 7, 1) + timedelta(days=r.randint(0, 91))
        amount = round(r.uniform(400, 9000), 2)
        if reg == "North":
            dv, av = d.strftime("%d/%m/%Y"), f"£{amount:,.2f}"
        elif reg == "South":
            dv, av = d, amount
        else:
            dv, av = d.isoformat(), f"{amount:,.2f}"
        if i % 37 == 5:
            av = f"({amount:,.2f})"  # a credit note in accounting brackets
        rows.append([dv, reg, r.choice(reps[reg]), f"Customer {r.randint(1, 40):02d}", av, r.choice([0, 0, 5, 10, 12.5])])
    rows[20][1] = " north "  # inconsistent case and spaces
    rows[41][4] = None  # missing amount
    rows.append(list(rows[10]))  # exact duplicate
    rows.append(list(rows[11]))
    write_table(ws, cols, rows, start_row=4, widths={"Customer": 16})
    ws.freeze_panes = None

    ws = wb.create_sheet("P&L")
    ws["A1"] = "Q3 P&L"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("B2:D2")
    ws["B2"] = "Quarter 3, 2026 (£000)"
    ws["B2"].alignment = Alignment(horizontal="center")
    items = [("Revenue", [412, 398, 455]), ("Cost of sales", [-221, -214, -240]), ("Gross profit", [191, 184, 215]),
             ("Overheads", [-132, -129, -138]), ("Operating profit", [59, 55, 77])]
    write_table(ws, ["", "Jul", "Aug", "Sep"], [[k, *v] for k, v in items], start_row=3)
    wb.save(OUT / "complex" / "messy-management-pack.xlsx")
    return {"regional_sales_rows": len(rows), "duplicates": 2, "credit_notes": sum(1 for x in rows if isinstance(x[4], str) and x[4].startswith("("))}


def bank_vs_ledger():
    """Bank statement vs cash book: matches, timing differences, typos, rounding, duplicates."""
    r = random.Random(808)
    ledger, bank = [], []
    for i in range(1, 181):
        ref = f"PAY-{26000 + i}"
        amount = round(r.uniform(85, 18500), 2)
        d = date(2026, 9, 1) + timedelta(days=r.randint(0, 29))
        ledger.append([d, ref, f"Supplier {r.randint(1, 45):02d}", amount])
        bank.append([d + timedelta(days=r.randint(0, 2)), ref, amount])
    cases = {}
    # 1. Payments in the cash book that have not cleared the bank yet (timing differences).
    cleared_late = [b[1] for b in bank[-6:]]
    bank = bank[:-6]
    cases["in_ledger_not_bank"] = cleared_late
    # 2. Bank charges and interest the cash book has not recorded.
    extras = [[date(2026, 9, 30), "BANK-CHG-0926", 42.5], [date(2026, 9, 30), "INT-0926", -18.73], [date(2026, 9, 15), "DD-INSURE-09", 1265.0]]
    bank += extras
    cases["in_bank_not_ledger"] = [e[1] for e in extras]
    # 3. Amounts keyed wrongly in the cash book's counterpart (90 out: a transposed-digit typo).
    for idx in (14, 77, 123):
        bank[idx][2] = round(bank[idx][2] + 90, 2)
    cases["amount_mismatch"] = [bank[i][1] for i in (14, 77, 123)]
    # 4. Penny rounding differences (cleared by a 0.01 tolerance).
    for idx in (30, 31):
        bank[idx][2] = round(bank[idx][2] + 0.01, 2)
    cases["rounding"] = [bank[i][1] for i in (30, 31)]
    # 5. A payment entered twice in the cash book.
    dup = list(ledger[60])
    ledger.append(dup)
    cases["duplicate_in_ledger"] = [dup[1]]
    # 6. References with stray spaces in the bank file (trimmed before matching).
    for idx in (5, 6, 7):
        bank[idx][1] = f" {bank[idx][1]} "

    wb = Workbook()
    ws = wb.active
    ws.title = "Cash book"
    write_table(ws, ["Date", "Reference", "Payee", "Amount"], ledger, formats={"Amount": GBP2})
    wb.save(OUT / "complex" / "cash-book-september.xlsx")
    pd.DataFrame(
        [[b[0].strftime("%d/%m/%Y"), b[1], f"{b[2]:.2f}" if b[2] >= 0 else f"({abs(b[2]):.2f})"] for b in bank],
        columns=["Transaction date", "Reference", "Amount"],
    ).to_csv(OUT / "complex" / "bank-statement-september.csv", index=False)
    return {"cash_book_rows": len(ledger), "bank_rows": len(bank), "planted": cases}


def intercompany():
    """Two group companies' views of the same balances; they should agree and do not."""
    r = random.Random(909)
    uk, de = [], []
    for i in range(1, 41):
        ref = f"IC-{2600 + i}"
        amount = round(r.uniform(2000, 60000), 2)
        uk.append([ref, "Northbridge GmbH", r.choice(["Management fee", "IT recharge", "Royalty", "Goods"]), amount])
        de.append([ref, "Northbridge UK Ltd", uk[-1][2], amount])
    de[8][3] = round(de[8][3] * 0.97, 2)  # booked at a different FX rate
    de[21][3] = round(de[21][3] - 5000, 2)  # part-payment netted off
    del de[33]  # invoice not yet booked by DE
    de.append(["IC-2699", "Northbridge UK Ltd", "Goods", 7340.0])  # booked by DE only
    for path, rows in (("intercompany-uk.xlsx", uk), ("intercompany-de.xlsx", de)):
        wb = Workbook()
        ws = wb.active
        ws.title = "Intercompany"
        write_table(ws, ["IC reference", "Counterparty", "Type", "Amount GBP"], rows, formats={"Amount GBP": GBP2}, widths={"Counterparty": 22})
        wb.save(OUT / "complex" / path)
    return {"uk_rows": len(uk), "de_rows": len(de)}


def main():
    (OUT / "complex").mkdir(parents=True, exist_ok=True)
    expected = {
        "law-firm-hartwell-lane.xlsx": law_firm(),
        "finance-northbridge-group.xlsx": finance(),
        "university-ashford.xlsx": university(),
        "insurance-kingsmere-claims.xlsx": insurance(),
        "manufacturing-corran-precision.xlsx": manufacturing(),
        "hr-fernhill-people.xlsx": hr(),
        "complex/messy-management-pack.xlsx": messy_pack(),
        "complex/bank-vs-cash-book": bank_vs_ledger(),
        "complex/intercompany": intercompany(),
    }
    (OUT / "expected.json").write_text(json.dumps(expected, indent=2, default=str) + "\n")
    print(json.dumps(expected, indent=2, default=str)[:4000])


if __name__ == "__main__":
    main()
