// Writes backend/tests/fixtures/unified_sql.json: the sample sources, the SQL meldra generates for a set of
// answers, and the numbers the browser engine gives. The backend test runs that SQL in the lakehouse (DuckDB)
// and checks it gives the same numbers, so the SQL shown to customers is correct in both places.
// Run: npx vite-node e2e/sql/make_fixture.mjs
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { columnsOf, compute, sanitize } from '../../src/lib/unifiedReporting/engine.js';
import { buildModel } from '../../src/lib/unifiedReporting/model.js';
import { buildSampleSources, sampleSuggestions } from '../../src/lib/unifiedReporting/sampleData.js';
import { specToSql } from '../../src/lib/unifiedReporting/sqlQuery.js';
import { SQL_CASES } from '../../src/lib/unifiedReporting/sqlCases.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const { sources, relationships } = buildSampleSources();
const m = buildModel(sources, relationships);
const csv = (s) => {
  const cell = (v) => { const t = v === null || v === undefined ? '' : String(v); return /[",\n]/.test(t) ? `"${t.replace(/"/g, '""')}"` : t; };
  const names = s.columns.map((c) => c.name);
  return [names.map(cell).join(','), ...s.rows.map((r) => s.columns.map((c) => cell(r[c.key])).join(','))].join('\n');
};
const cases = [...Object.entries(SQL_CASES).map(([name, spec]) => ({ title: name, ...spec })), ...sampleSuggestions(m).map((s) => s.spec)].map((raw) => {
  const sp = sanitize(raw, m);
  const res = compute(sp, m);
  const { sql } = specToSql(sp, m);
  return { title: sp.title, sql, labels: res.labels, columns: Object.fromEntries(columnsOf(res).map((c) => [c.label, c.data])) };
});
const out = {
  note: 'Generated by e2e/sql/make_fixture.mjs from src/lib/unifiedReporting (sample data). Do not edit by hand.',
  sources: sources.map((s) => ({ key: s.key, name: s.name, system: s.system, csv: csv(s) })),
  cases,
};
const file = path.join(HERE, '..', '..', 'backend', 'tests', 'fixtures', 'unified_sql.json');
fs.writeFileSync(file, `${JSON.stringify(out)}\n`);
console.log(`${cases.length} cases, ${sources.length} sources → ${path.relative(process.cwd(), file)} (${Math.round(fs.statSync(file).size / 1024)} KB)`);
